apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "curso_postgres.fullname" . }}
  labels:
    app: {{ include "curso_postgres.fullname" . }}
data:
  postgres_database: {{ .Values.postgresDatabase }}