apiVersion: v1
kind: Secret
metadata:
  name: {{ include "curso_postgres.fullname" . }}
  labels:
    app: {{ include "curso_postgres.fullname" . }}
data:
  postgres_user: {{ .Values.postgresUser | b64enc }}
  postgres_password: {{ .Values.postgresPassword | b64enc }}