apiVersion: v1
kind: Service
metadata:
  name: {{ include "curso_postgres.fullname" . }}
  labels:
    {{ include "curso_postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5432
      name: postgres
      protocol: TCP
  selector:
    app: {{ include "curso_postgres.fullname" . }}