apiVersion: v1
kind: Service
metadata:
  name: {{ include "curso_redis.fullname" . }}
  labels:
    {{ include "curso_redis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      name: redis
      protocol: TCP
  selector:
    app: {{ include "curso_redis.fullname" . }}