apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "curso_api.fullname" . }}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "curso_api.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60 # Escala si el uso promedio de CPU supera el 60%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70 # Escala si el uso promedio de memoria supera el 70%
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60 # Espera 60s antes de escalar hacia arriba
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15 # Aumenta hasta 1 pods cada 15s
    scaleDown:
      stabilizationWindowSeconds: 300 # Espera 5 min antes de reducir
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60 # Reduce 1 pod cada 60s