apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: curso-api-ingress
  annotations: 
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
spec:
  ingressClassName: nginx
  tls: {{ .Values.ingress.tls | toYaml | nindent 4 }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "curso_api.fullname" . }}
            port:
              number: {{ .Values.service.port }}