apiVersion: v1
kind: Secret
metadata:
  name: {{ include "curso_api.fullname" . }}
  labels:
    app: {{ include "curso_api.fullname" . }}
data:
  database-url: {{ .Values.postgres.connectionString | b64enc }}