apiVersion: v1
kind: Service
metadata:
  name: {{ include "curso_api.fullname" . }}
  labels:
    {{ include "curso_api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      name: http
      protocol: TCP
  selector:
    app: {{ include "curso_api.fullname" . }}