service:
  type: ClusterIP
  port: 80
ingress:
  host: api-curso.proyectosrandom.es
  clusterIssuer: letsencrypt-prod
  tls:
    - hosts:
      - api-curso.proyectosrandom.es
      secretName: api-curso-proyectosrandom-es-tls
#replicaCount: 2
hpa:
  minReplicas: 2
  maxReplicas: 6
image:
  repository: jvelascoiti/backend-fast-api
  tag: "1.0.2"
  pullPolicy: Always
resources:
  requests:
    cpu: "200m"
    memory: "256Mi"   
  limits:
    cpu: "200m"
    memory: "256Mi"
postgres:
  connectionString: "postgresql://postgres:1q2w3e4r5t6y@curso-postgres.default.svc.cluster.local:5432/curso_db"